id: P90945D91
initial_creation_type: input
source_metadata:
  title: Āryaśūra Series
  language: de
  description: Texts by the great Indian master Āryaśūra, known to Tibetans as Lobpon
    Pawo (slob dpon dpa' bo), author of the famous Garland of Birth Stories (Jātakamālā)
  volume:
    33827f59227c49f9a00b7a0ab492d6bd:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    1948c095593b4343985114c4a12a44ad:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T02:08:51.634273'
last_modified_at: '2022-03-01T02:08:51.634276'
